Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Style/MixinUsage:
  Exclude:
    - 'lib/remote_ruby.rb'

Security/MarshalLoad:
  Exclude:
    - 'lib/remote_ruby/unmarshaler.rb'

Layout/BlockAlignment:
  Exclude:
    - 'spec/remote_ruby/source_extractor_spec.rb'

Layout/IndentHeredoc:
  Exclude:
    - 'spec/remote_ruby/source_extractor_spec.rb'

Layout/IndentationWidth:
  Exclude:
    - 'spec/remote_ruby/source_extractor_spec.rb'

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/remote_ruby/source_extractor_spec.rb'

Lint/NonLocalExitFromIterator:
  Exclude:
    - 'spec/remote_ruby/source_extractor_spec.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/remote_ruby/source_extractor_spec.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'spec/remote_ruby/source_extractor_spec.rb'

