AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'shared_context']

Style/GlobalStdStream:
  Exclude:
    - spec/remote_ruby/connection_adapter/eval_adapter_spec.rb

Style/DocumentDynamicEvalDefinition:
  Enabled: false
