plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/AbcSize:
  Max: 22

Metrics/ClassLength:
  Max: 100

Metrics/MethodLength:
  Max: 24

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 30

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*_spec.rb'


RSpec/ContextWording:
  Prefixes:
    - and
    - with
    - because
    - when
    - without
    - shared

RSpec/RepeatedExampleGroupBody:
  Enabled: false
