plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 30

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  IgnoredMetadata:
    type:
      - integration

RSpec/ContextWording:
  Prefixes:
    - and
    - with
    - because
    - when
    - without

RSpec/RepeatedExampleGroupBody:
  Enabled: false
