plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'shared_context']
  Max: 30

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  Max: 6

Style/GlobalStdStream:
  Exclude:
    - spec/remote_ruby/connection_adapter/eval_adapter_spec.rb
