name: "Lint & Test"
on: [push, pull_request]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
          bundler-cache: true
      - run: bundle exec rubocop
  rspec:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: [2.7, 3.2, 3.3, head]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rspec
      - uses: coverallsapp/github-action@v2
